apiVersion: solution.sap/v1
kind: Solution

metadata:
  name: finance-controller-cost-center-ef35f
  version: "1.2.0"
  description: "AI agent enabling Finance Controllers to query SAP S/4HANA cost center data in natural language"

assets:
  - ref: ./assets/sap-s4-ce-costcenter-0001-mcp-server/asset.yaml
  - ref: ./assets/cost-center-querying-agent/asset.yaml
