name: Get IAS Token

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      cisTenantUrl:
        description: "Issuer URI of the SAP Cloud Identity Services tenant"
        default: "https://cicddev.accounts400.ondemand.com"
        required: true
      iasClientId:
        description: "Client ID of the IAS application"
        default: "febc3547-6af9-4085-9f10-a1ea136bd6bc"
        required: true

env:
  CIS_TENANT_URL: ${{ inputs.cisTenantUrl || 'https://cicddev.accounts400.ondemand.com' }}
  IAS_CLIENT_ID: ${{ inputs.iasClientId || 'febc3547-6af9-4085-9f10-a1ea136bd6bc' }}

jobs:
  do:
    runs-on: [solinas]
    # script based on: https://docs.github.com/en/enterprise-server@3.9/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Show provided parameters
        run: |
          echo "Provided parameters:"
          echo "- cisTenantUrl: $CIS_TENANT_URL"
          echo "- iasClientId: $IAS_CLIENT_ID"

      - name: Get short-lived GitHub-issued JWT
        id: get-github-jwt
        run: |
          githubJwt=$(curl -sS --fail -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$CIS_TENANT_URL" | jq -r '.value')
          echo $githubJwt | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
          echo "githubJwt=$githubJwt" >> $GITHUB_OUTPUT

      - name: Get IAS Token
        id: get-ias-token
        run: |
          response=$(
              curl -s -XPOST \
              -H 'Content-Type: application/x-www-form-urlencoded'\
              -d 'grant_type=client_credentials'\
              -d "client_id=$IAS_CLIENT_ID"\
              -d 'resource=urn:sap:identity:application:provider:name:joule-studio'\
              -d "client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer"\
              -d "client_assertion=${{steps.get-github-jwt.outputs.githubJwt}}"\
              $CIS_TENANT_URL/oauth2/token)
          ias_token=$(echo $response | jq -r .access_token)
          if [[ -z "$ias_token" || "$ias_token" = 'null' ]]; then
            echo "ias_token was not retrieved"
            echo "error response from IAS: $response"
            exit -1
          else
            echo "ias_token successfully retrieved"
            echo $ias_token | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
          fi
